feat(runes): add Get Tokens API
gaze-network/gaze-indexer pull request #38
Opened 2024-07-15 17:24 UTC by gazenw

## Description
- Implement Get Tokens API
  - Supports 2 scopes (`all` and `ongoing`)
    - `all` (DEFAULT) returns all rune entries, sorted by etching order
    - `ongoing` returns rune entries where mints < cap, sorted by mint progress (mint / cap)
  - Supports a search string, which does a prefix search on the rune name (spacers are trimed).
- Refactor other endpoints with pagination to use `paginationRequest` struct
- Add a GIN index on `runes_entries.rune` column to speed up `LIKE` operator.

## Type of change

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Enhancement (improvement to existing features and functionality)
- [ ] Documentation update (changes to documentation)
- [ ] Performance improvement (non-breaking change which improves efficiency)
- [ ] Code consistency (non-breaking change which improves code reliability and robustness)

## Commit formatting

Please follow the commit message conventions for an easy way to identify the purpose or intention of a commit. Check out our commit message conventions in the [CONTRIBUTING.md](https://github.com/gaze-network/gaze-indexer/blob/main/.github/CONTRIBUTING.md#pull-requests-or-commits)

2024-07-16 07:54 UTC, bombnp requested changes

2024-07-16 07:54 UTC, bombnp commented on modules/runes/database/postgresql/queries/data.sql
> +
count only latest balances for each (runeId, pkScript)

2024-10-06 11:52 UTC, Planxnx commented on modules/runes/api/httphandler/get_token_list.go
> +		blockHeight = uint64(blockHeader.Height)
```suggestion
		//nolint:gosec 
		blockHeight = uint64(blockHeader.Height)
```

2024-10-06 11:56 UTC, Planxnx requested changes

2024-10-06 11:56 UTC, Planxnx commented on modules/runes/api/httphandler/get_token_list.go
> +		panic("invalid scope")
shouldn't panic in http handler, do return `errs.InternError` or something instead

2024-10-06 11:56 UTC, Planxnx commented on modules/runes/api/httphandler/get_token_list.go
> +			DeployedAt:        uint64(ent.EtchedAt.Unix()),
use `int64` for unix timestamp value

2024-10-06 12:20 UTC, Planxnx approved these changes

2024-10-06 12:30 UTC, merged